[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  weight = 20

[[main]]
  name = "CI/CD"
  parent = "Topics"
  pageRef = "tags/ci-cd"
  weight = 10

[[main]]
  name = "Cloud"
  parent = "Topics"
  pageRef = "tags/cloud"
  weight = 20

[[main]]
  name = "Automation"
  parent = "Topics"
  pageRef = "tags/automation"
  weight = 30

[[main]]
  name = "All Tags"
  parent = "Topics"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "Series"
  pageRef = "/series"
  weight = 30

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 40