[[main]]
  name = "Bài viết"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Chủ đề"
  weight = 20

[[main]]
  name = "CI/CD"
  parent = "Chủ đề"
  pageRef = "tags/ci-cd"
  weight = 10

[[main]]
  name = "Cloud"
  parent = "Chủ đề"
  pageRef = "tags/cloud"
  weight = 20

[[main]]
  name = "Automation"
  parent = "Chủ đề"
  pageRef = "tags/automation"
  weight = 30

[[main]]
  name = "Tất cả thẻ (Tags)"
  parent = "Chủ đề"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "Chuỗi bài (Series)"
  pageRef = "series"
  weight = 30
